# Generated by Django 5.0.1 on 2024-01-30 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_remove_customer_password'),
    ]

    operations = [
        migrations.RenameField(
            model_name='payments',
            old_name='payment_category',
            new_name='payment_duration',
        ),
        migrations.AddField(
            model_name='payments',
            name='amount_paid',
            field=models.IntegerField(default=0),
        ),
    ]
