# Generated by Django 5.0.1 on 2024-09-27 18:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_alter_agent_agent_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Test',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount_paid', models.IntegerField(default=0)),
                ('payment_duration', models.IntegerField(default=0)),
                ('description', models.CharField(blank=True, max_length=200, null=True)),
                ('payment_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('expiry_date', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(blank=True, max_length=20, null=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='test', to='dashboard.customer')),
            ],
        ),
    ]
