# Generated by Django 5.0.1 on 2024-02-05 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0004_rename_payment_category_payments_payment_duration_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='payment_category',
            field=models.IntegerField(default=0),
        ),
    ]
