# Generated by Django 5.0.1 on 2024-02-05 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0005_alter_customer_payment_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payments',
            name='payment_duration',
            field=models.IntegerField(default=0),
        ),
    ]
