# Generated by Django 5.0.1 on 2024-02-26 03:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0007_alter_payments_payment_duration'),
    ]

    operations = [
        migrations.AddField(
            model_name='payments',
            name='expiry_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='payments',
            name='payment_duration',
            field=models.IntegerField(default=0),
        ),
    ]
