# Generated by Django 5.0.1 on 2024-09-30 22:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0007_customer_activation_expiry'),
    ]

    operations = [
        migrations.AddField(
            model_name='agent',
            name='status',
            field=models.IntegerField(choices=[(1, 'Active'), (0, 'Suspended')], default=0),
        ),
    ]
