# Generated by Django 5.0.1 on 2024-02-26 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0008_payments_expiry_date_alter_payments_payment_duration'),
    ]

    operations = [
        migrations.AddField(
            model_name='payments',
            name='status',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
