# Generated by Django 5.0.1 on 2024-02-26 11:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0009_payments_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='payments',
            name='received_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='received_payments', to='dashboard.agent'),
        ),
    ]
