# Generated by Django 5.0.1 on 2024-02-27 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0010_payments_received_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='admin',
            name='phone_nunmber',
            field=models.CharField(max_length=11, null=True),
        ),
        migrations.AddField(
            model_name='agent',
            name='phone_nunmber',
            field=models.CharField(max_length=11, null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='phone_nunmber',
            field=models.CharField(max_length=11, null=True),
        ),
    ]
