# Generated by Django 5.0.1 on 2024-03-04 12:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0011_admin_phone_nunmber_agent_phone_nunmber_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='phone_nunmber',
            new_name='phone_number',
        ),
    ]
