# Generated by Django 5.0.1 on 2024-03-04 13:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0012_rename_phone_nunmber_customer_phone_number'),
    ]

    operations = [
        migrations.RenameField(
            model_name='agent',
            old_name='phone_nunmber',
            new_name='phone_number',
        ),
    ]
